/* ============================================================== */
/* CLEANUP (DROP EXISTING TABLES & CONSTRAINTS)                   */
/* ============================================================== */
BEGIN
   FOR t IN (SELECT table_name FROM user_tables WHERE table_name IN (
      'DETIL_JENIS_POSISI_EVENT', 'KEAKTIFAN_MAHASISWA', 'MAHASISWA_BERPRESTASI',
      'NILAI', 'PLOTTING_AJAR', 'MAHASISWA', 'MATAKULIAH', 'EVENT', 
      'JENIS_POS_EVENT', 'DOSEN', 'PROGRAM_STUDI'
   )) LOOP
      EXECUTE IMMEDIATE 'DROP TABLE "' || t.table_name || '" CASCADE CONSTRAINTS PURGE';
   END LOOP;
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/

/* ============================================================== */
/* CREATE TABLES                                                  */
/* ============================================================== */

CREATE TABLE PROGRAM_STUDI (
   KODE_PRODI           VARCHAR2(5)          NOT NULL,
   NAMA_PRODI           VARCHAR2(35)         NOT NULL,
   MASA_TAHUN_STUDI     NUMBER(1),
   CONSTRAINT PK_PROGRAM_STUDI PRIMARY KEY (KODE_PRODI)
);

CREATE TABLE DOSEN (
   NID                  VARCHAR2(6)          NOT NULL,
   NAMA_DOSEN           VARCHAR2(60)         NOT NULL,
   CONSTRAINT PK_DOSEN PRIMARY KEY (NID)
);

CREATE TABLE EVENT (
   ID_EVENT             VARCHAR2(5)          NOT NULL,
   NAMA_EVENT           VARCHAR2(50)         NOT NULL,
   TANGGAL_EVENT        DATE                 NOT NULL,
   CONSTRAINT PK_EVENT PRIMARY KEY (ID_EVENT)
);

CREATE TABLE JENIS_POS_EVENT (
   ID_JENIS             NUMBER(2)            NOT NULL,
   NAMA_JENIS           VARCHAR2(30)         NOT NULL,
   CONSTRAINT PK_JENIS_POS_EVENT PRIMARY KEY (ID_JENIS)
);

CREATE TABLE DETIL_JENIS_POSISI_EVENT (
   ID_JENIS             NUMBER(2)            NOT NULL,
   ID_EVENT             VARCHAR2(5)          NOT NULL,
   SSKM                 NUMBER(2)            NOT NULL,
   CONSTRAINT PK_DETIL_JENIS_POSISI_EVENT PRIMARY KEY (ID_JENIS, ID_EVENT)
);

CREATE TABLE MAHASISWA (
   NIM                  VARCHAR2(11)         NOT NULL,
   KODE_PRODI           VARCHAR2(5)          NOT NULL,
   NAMA_DEPAN           VARCHAR2(30),
   NAMA_BELAKANG        VARCHAR2(40)         NOT NULL,
   ALAMAT_TINGGAL       VARCHAR2(50)         NOT NULL,
   KOTA_TINGGAL         VARCHAR2(30)         NOT NULL,
   NO_TELP_AKTIF        VARCHAR2(15)         NOT NULL,
   JENIS_KELAMIN        CHAR(1)              NOT NULL,
   STATUS_NIKAH         CHAR(1)              NOT NULL,
   STATUS_MHS           CHAR(1)              NOT NULL,
   TGL_LAHIR            DATE                 NOT NULL,
   CONSTRAINT PK_MAHASISWA PRIMARY KEY (NIM)
);

CREATE TABLE KEAKTIFAN_MAHASISWA (
   NIM                  VARCHAR2(11)         NOT NULL,
   ID_JENIS             NUMBER(2)            NOT NULL,
   ID_EVENT             VARCHAR2(5)          NOT NULL,
   CONSTRAINT PK_KEAKTIFAN_MAHASISWA PRIMARY KEY (NIM, ID_JENIS, ID_EVENT)
);

CREATE TABLE MAHASISWA_BERPRESTASI (
   NIM                  VARCHAR2(11)         NOT NULL,
   PERIODE_TAHUN        VARCHAR2(11)         NOT NULL,
   NAMA_LENGKAP         VARCHAR2(60)         NOT NULL,
   CONSTRAINT PK_MAHASISWA_BERPRESTASI PRIMARY KEY (NIM, PERIODE_TAHUN)
);

CREATE TABLE MATAKULIAH (
   KODE_MK              VARCHAR2(5)          NOT NULL,
   MK_SYARAT            VARCHAR2(5),
   NAMA_MK              VARCHAR2(30)         NOT NULL,
   SKS                  NUMBER(2)            NOT NULL,
   SEMESTER             NUMBER(2)            NOT NULL,
   GRADE_MINIMUM        VARCHAR2(2),
   CONSTRAINT PK_MATAKULIAH PRIMARY KEY (KODE_MK)
);

CREATE TABLE NILAI (
   NIM                  VARCHAR2(11)         NOT NULL,
   NID                  VARCHAR2(6)          NOT NULL,
   KODE_MK              VARCHAR2(5)          NOT NULL,
   TUGAS                NUMBER(3),
   UTS                  NUMBER(3),
   UAS                  NUMBER(3),
   CONSTRAINT PK_NILAI PRIMARY KEY (NIM, NID, KODE_MK)
);

CREATE TABLE PLOTTING_AJAR (
   KODE_MK              VARCHAR2(5)          NOT NULL,
   NID                  VARCHAR2(6)          NOT NULL,
   ID_PLOT              VARCHAR2(5)          NOT NULL,
   HARI                 VARCHAR2(10)         NOT NULL,
   JAM_MULAI            VARCHAR2(5)          NOT NULL,
   JAM_SELESAI          VARCHAR2(5)          NOT NULL,
   CONSTRAINT PK_PLOTTING_AJAR PRIMARY KEY (KODE_MK, NID, ID_PLOT)
);

/* ============================================================== */
/* ADD FOREIGN KEYS                                               */
/* ============================================================== */

ALTER TABLE DETIL_JENIS_POSISI_EVENT
   ADD CONSTRAINT FK_DETIL_JE_EV_HAS_PO_EVENT FOREIGN KEY (ID_EVENT)
      REFERENCES EVENT (ID_EVENT);

ALTER TABLE DETIL_JENIS_POSISI_EVENT
   ADD CONSTRAINT FK_DETIL_JE_POS_HAS_P_JENIS_PO FOREIGN KEY (ID_JENIS)
      REFERENCES JENIS_POS_EVENT (ID_JENIS);

ALTER TABLE KEAKTIFAN_MAHASISWA
   ADD CONSTRAINT FK_KEAKTIFA_MHS_HAS_P_MAHASISW FOREIGN KEY (NIM)
      REFERENCES MAHASISWA (NIM);

ALTER TABLE KEAKTIFAN_MAHASISWA
   ADD CONSTRAINT FK_KEAKTIFA_PART_HAS__DETIL_JE FOREIGN KEY (ID_JENIS, ID_EVENT)
      REFERENCES DETIL_JENIS_POSISI_EVENT (ID_JENIS, ID_EVENT);

ALTER TABLE MAHASISWA
   ADD CONSTRAINT FK_MAHASISW_PRODI_HAS_PROGRAM_ FOREIGN KEY (KODE_PRODI)
      REFERENCES PROGRAM_STUDI (KODE_PRODI);

ALTER TABLE MAHASISWA_BERPRESTASI
   ADD CONSTRAINT FK_MAHASISW_MHS_HAS_A_MAHASISW FOREIGN KEY (NIM)
      REFERENCES MAHASISWA (NIM);

ALTER TABLE MATAKULIAH
   ADD CONSTRAINT FK_MATAKULI_MK_HAS_RE_MATAKULI FOREIGN KEY (MK_SYARAT)
      REFERENCES MATAKULIAH (KODE_MK);

ALTER TABLE NILAI
   ADD CONSTRAINT FK_NILAI_DOSEN_GIV_DOSEN FOREIGN KEY (NID)
      REFERENCES DOSEN (NID);

ALTER TABLE NILAI
   ADD CONSTRAINT FK_NILAI_MHS_HAS_S_MAHASISW FOREIGN KEY (NIM)
      REFERENCES MAHASISWA (NIM);

ALTER TABLE NILAI
   ADD CONSTRAINT FK_NILAI_MK_HAS_SC_MATAKULI FOREIGN KEY (KODE_MK)
      REFERENCES MATAKULIAH (KODE_MK);

ALTER TABLE PLOTTING_AJAR
   ADD CONSTRAINT FK_PLOTTING_DOSEN_HAS_DOSEN FOREIGN KEY (NID)
      REFERENCES DOSEN (NID);

ALTER TABLE PLOTTING_AJAR
   ADD CONSTRAINT FK_PLOTTING_MK_HAS_PL_MATAKULI FOREIGN KEY (KODE_MK)
      REFERENCES MATAKULIAH (KODE_MK);